### ISSUE TITLE
Add rule for preventing duplicate ESLint configs

### ISSUE THREAD

**Issue by karlhorky** [upleveled/preflight#140]
Next.js has a default configuration `.eslintrc.json` which is confusing when the student has also installed the UpLeveled ESLint config and it has created `.eslintrc.cjs`.

Let's fail when the user has multiple ESLint configs (matching any valid name).

Maybe there's a package / import from ESLint for this, that will list out all the valid config names.

Related: Delete the `.eslintrc.json` from Next.js upon installation of the UpLeveled ESLint config: https://github.com/upleveled/eslint-config-upleveled/issues/74

**Comment by Josehower** [comment]
Related to #20 #21 #19

**Comment by karlhorky** [comment]
We now use the `--no-eslint` flag with `create-next-app`, which avoids creation of this other configuration file.
