### ISSUE TITLE
Switch from Algolia to package.json info in registry?

### ISSUE THREAD

**Issue by karlhorky** [upleveled/preflight#211]
Right now, we're using Algolia to get the DefinitelyTyped data:

https://github.com/upleveled/preflight/blob/488fb0c2fd82469ca2ac2ccc891712651d9eea3e/src/checks/noDependencyProblems/noDependenciesWithoutTypes.ts#L13

Maybe we can get this from `npm` and `package.json` now?

https://github.com/npm/rfcs/commit/61e62a671cd957e92e68f97a7b1ec554b81c10c5

**Comment by karlhorky** [comment]
This does not include all information for a library that includes types, eg https://registry.npmjs.org/yup/0.32.11

**Comment by karlhorky** [comment]
Looks like the following PR should fix it (and should be effective tomorrow):

- https://github.com/algolia/npm-search/pull/1140

**Comment by pixelastic** [comment]
Hey @karlhorky, the data should now be live and updated in the index. Could you let us know if it solves you issues?

All packages (with their latest versions), should be included, as well as up-to-date type information.

**Comment by Eprince-hub** [comment]
@pixelastic Thanks for the update
I tested by running Preflight with `smart-image-saver`, and it now runs without the `ObjectID does not exist` error

```bash
🚀 UpLeveled Preflight v2.0.0
✔ All changes committed to Git
✔ node_modules/ folder ignored in Git
✔ No extraneous files committed to Git
✔ No secrets committed to Git
✔ Use single package manager
✔ Project folder name matches correct format
✔ No dependency problems
✖ GitHub repo has deployed project link under About
  › Deployed project link not found in About section on
    https://github.com/Eprince-hub/test-smart-image-algolia-check. Click on the cog symbol to the right
    of the About heading and paste the Repl.it / Netlify / Fly.io link in the Website box.
✔ ESLint
✔ Prettier
✔ ESLint config is latest version
✖ Preflight is latest version
  › Your current version of Preflight (2.0.0) is older than the latest version 2.1.17 - upgrade with:

    ‎  $ pnpm add --global @upleveled/preflight
```
