### ISSUE TITLE
New Feature: allow Docker container run preflight on a different branch

### ISSUE THREAD

**Issue by Josehower** [upleveled/preflight#219]
It would be handy and nice to be able to use the docker container for preflight on a different branch

as it is now docker container run preflight on the main/master branch of a repo URL under this command

`docker run preflight myusername/myrepo`

The feature required would be something that allows me to define the branch I want to test preflight on

`docker run preflight myusername/myrepo#branch-name`

A good use case for this feature would be using Docker container to test PR branches from a GitHub action.

Currently, we have this issue on the Portfolios tests failing on every bot request.

a draft  for the PR workflow would be: 

on the [docker script file:](https://github.dev/upleveled/preflight/blob/2851355ed7311990508173f223788bd204931a43/docker/clone-and-preflight.ts#L31-L33)

1. get the branch name from the # tag
2. validate the url before the hash
3. update clone command to accept clone [from a branch ](https://www.freecodecamp.org/news/git-clone-branch-how-to-clone-a-specific-branch/) (e.g git clone -b <branchname> <remote-repo-url>)

**Comment by karlhorky** [comment]
Done in #347
