### ISSUE TITLE
VS Code Prettier extension version 10.1.0 conflicts with Prettier v3 in Preflight

### ISSUE THREAD

**Issue by ProchaLu** [upleveled/preflight#429]
Formatting with VS Code Prettier extension `v10.1.0` (latest on [Prettier VS Code extension page](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) as of Aug 2023) causes issues with Preflight because `v10.1.0` uses Prettier `v2.x` and Preflight uses Prettier `v3.0.2` 
```
✖ Prettier
  › Prettier has not been run in the following files:
    components/styles/chips.styles.ts

    For each of the files above, open the file in your editor and save the file. This will format the file with Prettier, which will cause changes
    to appear in Git.

    In some very uncommon cases (this probably doesn't apply to you), the mismatch may come from inconsistent end of line characters. Read more
    here: https://github.com/upleveled/answers/issues/31
```

For a workaround, revert to Prettier VSCode Extension version `v10.0.0`. An update of the Prettier VSCode Extension is expected to rectify the compatibility issue. Currently, it's not possible to transition to Prettier VSCode Extension version v10.2.0 preview. Relevant information can be found in [Karl's comment in the `prettier-vscode` PR](https://github.com/prettier/prettier-vscode/pull/3069#issuecomment-1688345990).

The [styling in the `components/styles/chips.styles.ts` file](https://github.com/upleveled/next-starter-peacock/blob/ec632fdd50171863cdec5aa1954cdcddbcaebed3/components/styles/chips.styles.ts#L17-L19) in [`next-starter-peacock portfolio`](https://github.com/upleveled/next-starter-peacock) is causing this issue with Preflight. VS Code Prettier extension `v10.1.0` formats:
```
transition: transform 0.15s, color 0.15s;
```
Prettier `v3.0.2` formats:
```
    transition:
      transform 0.15s,
      color 0.15s;
```

**Comment by karlhorky** [comment]
Created a full issue to track this problem now, since it's pretty easy to make the extension crash with an ESM config:

- https://github.com/prettier/prettier-vscode/issues/3298

**Comment by karlhorky** [comment]
Decided to just install `prettier` during UpLeveled ESLint config install:

- https://github.com/upleveled/eslint-config-upleveled/issues/332
